### ISSUE TITLE
Unexpected character encountered while parsing value: S. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by Katarn** [impworks/bonsai#107]
На последнем докер-образе ловлю такое:

```
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Bonsai.Data.Utils.Seed.SeedContext.AddPage(String title, Nullable`1 gender, String birth, String death, PageType type, String descrSource, String factsSource) in /build/Data/Utils/Seed/SeedContext.cs:line 40
   at Bonsai.Data.Utils.Seed.SeedData.EnsureSampleDataSeeded(AppDbContext db, ElasticService elastic) in /build/Data/Utils/Seed/SeedData.cs:line 21
   at Bonsai.Code.Config.Startup.InitDatabase(IApplicationBuilder app) in /build/Code/Config/Startup.Database.cs:line 68
   at Bonsai.Code.Config.Startup.Configure(IApplicationBuilder app) in /build/Code/Config/Startup.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Bonsai.Program.Main(String[] args) in /build/Program.cs:line 30
```

**Comment by impworks** [comment]
Во время рефакторинга в конфиг проскочила настройка, которая закидывает в базу тестовые данные. К счастью, самих тестовых данных в докер-образе не было, и приложение упало.

Я выпилил настройку из конфига в коммите e745a4ffe15c4ec5e6a4bb3b1481f8b1b99a9dfb - на нем все должно работать.
