### ISSUE TITLE
Цикличный рестарт контейнеров

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#123]
Запуск композера в случае замены named volume на относительный пути к папке которая находится в папке в которой  производится запуск приводит к цикличной перезагрузке контейнеров на третьем старте
@DiverOfDark

**Comment by DiverOfDark** [comment]
Можно приложить:
1) Лог контейнера(ов) которые падают
2) Подробности окружения - какая ОС (linux, windows, wsl, wsl2, mac?), какая файловая система в папке?

**Comment by centralhardware** [comment]
KUbuntu 19.10, ext4/cifs 
Ошибки
 unable to find ip ...(очень много)
И какие то ещё dotnet выбрасывает

**Comment by centralhardware** [comment]
На втором запуске ошибки через пару минут проходят, на третьем в какой то момент контейнер выходить с 1xx кодом выхода и все начинается по новой

**Comment by centralhardware** [comment]
на docker for window via hyper-v проблема не проявляется

**Comment by centralhardware** [comment]
https://pastebin.com/7Pfvzw49

**Comment by centralhardware** [comment]
```
bonsai_1    | Unhandled Exception: System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
bonsai_1    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
bonsai_1    |    --- End of inner exception stack trace ---
bonsai_1    |    at Bonsai.Code.Services.Elastic.ElasticService.EnsureIndexesCreated(AppDbContext db) in /build/Code/Services/Elastic/ElasticService.cs:line 120
bonsai_1    |    at Bonsai.Code.Config.Startup.InitDatabase(IApplicationBuilder app) in /build/Code/Config/Startup.Database.cs:line 69
bonsai_1    |    at Bonsai.Code.Config.Startup.Configure(IApplicationBuilder app) in /build/Code/Config/Startup.cs:line 65
bonsai_1    | --- End of stack trace from previous location where exception was thrown ---
bonsai_1    |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
bonsai_1    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
bonsai_1    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
bonsai_1    |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
bonsai_1    |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
bonsai_1    |    at Bonsai.Program.Main(String[] args) in /build/Program.cs:line 33
traefik_1   | time="2020-01-13T12:15:12Z" level=error msg="unable to find the IP address for the container \"/bonsai_elastic_1\": the server is ignored" container=elastic-bonsai-82af0ec1b9915ddd04699a9706a381413697a52f6112e11498fc24fc90a644a0 providerName=docker
traefik_1   | time="2020-01-13T12:15:12Z" level=error msg="unable to find the IP address for the container \"/bonsai_bonsai_1\": the server is ignored" providerName=docker container=bonsai-bonsai-6725ed2863d887d6f365d5a68820f6fae6fbbd9ce3da62791d2005711260c668
traefik_1   | time="2020-01-13T12:15:12Z" level=error msg="unable to find the IP address for the container \"/bonsai_elastic_1\": the server is ignored" providerName=docker container=elastic-bonsai-82af0ec1b9915ddd04699a9706a381413697a52f6112e11498fc24fc90a644a0
traefik_1   | time="2020-01-13T12:15:12Z" level=error msg="the router bonsai_secure@docker uses a non-existent resolver: le"
traefik_1   | time="2020-01-13T12:15:14Z" level=error msg="unable to find the IP address for the container \"/bonsai_elastic_1\": the server is ignored" providerName=docker container=elastic-bonsai-82af0ec1b9915ddd04699a9706a381413697a52f6112e11498fc24fc90a644a0
traefik_1   | time="2020-01-13T12:15:16Z" level=error msg="the router bonsai_secure@docker uses a non-existent resolver: le"
bonsai_bonsai_1 exited with code 139

```
момент падения bonsai

**Comment by centralhardware** [comment]
`bonsai_elastic_1 exited with code 1
`

**Comment by centralhardware** [comment]
может быть traefic и не падает

**Comment by centralhardware** [comment]
https://github.com/approximatenumber/compose-backuper-script
организовал бекап с помощью данного проекта

**Comment by DiverOfDark** [comment]
Судя по логам выглядело будто файловых прав не хватало эластику писать в папку, которую подмонтировали вместо volume.
