### ISSUE TITLE
ошибка при загрузке видео

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#125]
```
bonsai_1    | [16:27:48 ERR] An unhandled exception has occurred while executing the request.
bonsai_1    | Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large.
bonsai_1    |    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
bonsai_1    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.ForContentLength.OnReadStarting()
bonsai_1    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.TryInit()
bonsai_1    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.EnsureBufferedAsync(Int32 minCount, CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
bonsai_1    |    at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
bonsai_1    |    at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
bonsai_1    |    at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ControllerContext controllerContext)
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
bonsai_1    | --- End of stack trace from previous location where exception was thrown ---
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
bonsai_1    |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
bonsai_1    |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
bonsai_1    |    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
bonsai_1    |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
bonsai_1    |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
bonsai_1    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
bonsai_1    |    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
bonsai_1    |    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
bonsai_1    |    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

размер загружаемог файла 838 МБ

**Comment by impworks** [comment]
Снято ограничение на максимальный размер загружаемого файла.

Возможно, для #120 было бы полезно иметь настройку, ограничивающую размер загружаемых файлов (или запрещающих это насовсем). Но это нужно делать только после #99.
