### ISSUE TITLE
Ошибка генерации генеалогического дерева

### ISSUE THREAD

**Issue by centralhardware** [impworks/bonsai#158]
При значениях "Построения дерева"

![image](https://user-images.githubusercontent.com/26829359/88459313-9c52c680-cebe-11ea-8cac-bb478cdf517e.png)

 выше чем возникает исключение:

```
[14:22:58 ERR] Failed to generate a tree layout.
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: The Node invocation timed out after 60000ms.
You can change the timeout duration by setting the InvocationTimeoutMilliseconds property on NodeServicesOptions.

The first debugging step is to ensure that your Node.js function always invokes the supplied callback (or throws an exception synchronously), even if it encounters an error. Otherwise, the .NET code has no way to know that it is finished or has failed.
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Bonsai.Areas.Admin.Logic.TreeLayoutService.RenderTree(INodeServices js, TreeLayoutVM tree) in /build/Bonsai/Areas/Admin/Logic/TreeLayoutService.cs:line 295
   at Bonsai.Areas.Admin.Logic.TreeLayoutService.ProcessAsync(IServiceProvider services) in /build/Bonsai/Areas/Admin/Logic/TreeLayoutService.cs:line 86

```

PS 110 связей

**Comment by impworks** [comment]
Поставил таймаут в 30 минут - должно хватить.
